---
title: "Projects Overview"
subtitle: "Here is an overview of the project we have been working on."
---

## [High-Resolution Map of Climate Change Perception in China](/maps)

Our research presents a high-resolution map that showcases the regional disparities in climate change perception across China. This map, the first of its kind, offers a detailed view of how climate change concerns vary from one province to another, and even from one city to the next.


## [Mental Images of Climate Change Awareness in China](/images)

Previous studies suggest optimistically high climate change awareness in China, theworld's largest carbon emitter Yet it is unknown how the discourse is interpreted byindividual's own frame, due to largely adopted Yes-No survey design. This study, for thefirst time, performed a nationwide open-ended survey covering 4,037 respondents,identifies seven distinct mental images that exclusively represent Chinese residents'conceptualization of climate change, including global warming, distant icons, naturaldisasters, environmental degradation, cause, solution, and weather. 




::: {.callout-note collapse="true"}
### Publications

1. Yang, J., Gounaridis, D., Liu, M., Bi, J., & Newell, J. P. (2021). Perceptions of climate change in China: evidence from surveys of residents in six cities. Earth's Future, 9(12), e2021EF002144. [PDF](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2021EF002144?af=R)
2. Xia, Z., Ye, J., Marlon, J., Dong, X., Xie, J., Tian, X., ... & Liu, M. (2023). Growing climate change concern but rising regional disparities in China. [PDF](https://www.researchsquare.com/article/rs-3130454/v1)
3. Xia, Z., Ye, J., Zhou, Y., Howe, P. D., Xu, M., Tan, X., ... & Zhang, C. (2022). A meta-analysis of the relationship between climate change experience and climate change perception. Environmental Research Communications, 4(10), 105005. [PDF](https://iopscience.iop.org/article/10.1088/2515-7620/ac9bd9/meta)

:::
